function D = D(u,v,r)
%D
%    D = D(U,V,R)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    29-Jan-2019 10:59:50

t2 = abs(r);
t3 = abs(v);
D = reshape([abs(u).*(-3.545e-1)+u.^2.*3.787+6.555e-1,0.0,0.0,0.0,t2.*(1.61e2./2.0e2)+t3.*(3.47e2./1.25e2)+v.^2.*6.491e1+1.33e2./1.0e2,t2.*(-1.3e1./1.0e2)+t3.*2.088e-1,0.0,t2.*(6.9e1./2.0e1)+t3.*(1.69e2./2.0e2)+2.9e1./4.0,t2.*(3.0./4.0)-t3.*(2.0./2.5e1)+1.9e1./1.0e1],[3,3]);
